Repository fga-gpp-mds/2018.1-VoxPop-WebApp, pull requests merged in 2018-06, with the labels that each got.

#135 USF22/ver ranking de compatibilidade
  src/app/app.module.ts
  src/app/main-page/main-page.component.html
  src/app/minhas-pls/minhas-pls.component.css
  src/app/minhas-pls/minhas-pls.component.html
  src/app/minhas-pls/minhas-pls.component.spec.ts
  src/app/minhas-pls/minhas-pls.component.ts
  src/app/requests.service.ts
  src/app/see-compatible-parliamenterian/see-compatible-parliamenterian.component.css
  src/app/see-compatible-parliamenterian/see-compatible-parliamenterian.component.html
  src/app/see-compatible-parliamenterian/see-compatible-parliamenterian.component.spec.ts
  src/app/see-compatible-parliamenterian/see-compatible-parliamenterian.component.ts
  src/app/see-pl/see-pl.component.spec.ts
Labels: MDS, devops, front end, moderate difficulty, new feature

#141 Usability
  docs/eps/cronograma.md
  docs/eps/images/Login.png
  docs/eps/images/cadastro.png
  docs/eps/images/criar-cadastro.png
  docs/eps/images/data-de-nascimento.png
  docs/eps/images/dias-explicitos.png
  docs/eps/images/editar.png
  docs/eps/images/fora-da-caixa.png
  docs/eps/images/meus-votos.png
  docs/eps/images/meus_votos.png
  docs/eps/images/pagina_inicial.png
  docs/eps/images/pagina_inicial_logado.png
  docs/eps/images/proposicao.png
  docs/eps/images/seguir-deputado.png
  docs/eps/images/votar.png
  docs/eps/usabilidade.md
Labels: EPS, doc, front end, simple difficulty

#140 Usf18/ver estatisticas
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/propositions/propositions.component.css
  src/app/propositions/propositions.component.html
  src/app/propositions/propositions.component.spec.ts
  src/app/propositions/propositions.component.ts
  src/models/proposition.ts
Labels: MDS, evolution, front end, new feature, simple difficulty

#154 USF24 - Entre em Contato Conosco
  src/app/app.module.ts
  src/app/contact-us/contact-us.component.css
  src/app/contact-us/contact-us.component.html
  src/app/contact-us/contact-us.component.spec.ts
  src/app/contact-us/contact-us.component.ts
  src/app/requests.service.spec.ts
  src/app/requests.service.ts
  src/app/sidebar/sidebar.component.html
  src/models/message.ts
Labels: MDS, Style, front end, moderate difficulty, new feature

#170 USF26 – Ver análise social de uma proposição
  src/app/app.module.ts
  src/app/header/header.component.spec.ts
  src/app/minhas-pls/minhas-pls.component.spec.ts
  src/app/proposition/proposition.component.css
  src/app/proposition/proposition.component.html
  src/app/proposition/proposition.component.spec.ts
  src/app/proposition/proposition.component.ts
  src/app/requests.service.spec.ts
  src/app/requests.service.ts
  src/app/see-pl/see-pl.component.html
  src/app/user-following/user-following.component.spec.ts
Labels: MDS, evolution, front end, moderate difficulty, new feature, research
