Repository fga-gpp-mds/2018.1-VoxPop-WebApp, pull requests merged in 2018-05, with the labels that each got.

#98 USF12 listar todos deputados
  src/app/app.module.ts
  src/app/parliamentarian/parliamentarian.component.css
  src/app/parliamentarian/parliamentarian.component.html
  src/app/parliamentarian/parliamentarian.component.spec.ts
  src/app/parliamentarian/parliamentarian.component.ts
  src/app/requests.service.ts
Labels: enhancement

#101 BF01/Bug Na Edição de Voto
  src/app/minhas-pls/minhas-pls.component.html
  src/app/minhas-pls/minhas-pls.component.ts
  src/app/requests.service.ts
  src/app/see-pl/see-pl.component.css
  src/app/see-pl/see-pl.component.html
  src/app/see-pl/see-pl.component.ts
Labels: MDS, bug, evolution, front end, refactor

#103 Usf20/visualizar ultimas proposições
  src/app/main-page/main-page.component.css
  src/app/main-page/main-page.component.html
  src/app/main-page/main-page.component.ts
  src/app/requests.service.ts
Labels: MDS, Style, front end, moderate difficulty, new feature

#105 Vote proposition style
  src/app/propositions/propositions.component.css
  src/app/propositions/propositions.component.html
Labels: MDS, Style, front end, refactor, simple difficulty

#106 Usf14merge
  src/app/app.module.ts
  src/app/parliamentarian/parliamentarian.component.html
  src/app/requests.service.ts
  src/app/see-politician-detail/see-politician-detail.component.css
  src/app/see-politician-detail/see-politician-detail.component.html
  src/app/see-politician-detail/see-politician-detail.component.spec.ts
  src/app/see-politician-detail/see-politician-detail.component.ts
  src/models/parlimentarian.ts
Labels: MDS, front end, new feature, simple difficulty

#107 Usf19/procurar deputado
  src/app/parliamentarian/parliamentarian.component.css
  src/app/parliamentarian/parliamentarian.component.html
  src/app/parliamentarian/parliamentarian.component.ts
  src/app/requests.service.ts
Labels: MDS, front end, moderate difficulty, new feature

#109 Usf13/listar deputados seguidos
  src/app/app.module.ts
  src/app/requests.service.ts
  src/app/user-following/user-following.component.css
  src/app/user-following/user-following.component.html
  src/app/user-following/user-following.component.spec.ts
  src/app/user-following/user-following.component.ts
Labels: MDS, devops, front end, new feature, simple difficulty

#112 Usf15/seguir deputado
  src/app/requests.service.ts
  src/app/see-politician-detail/see-politician-detail.component.css
  src/app/see-politician-detail/see-politician-detail.component.html
  src/app/see-politician-detail/see-politician-detail.component.ts
Labels: MDS, front end, moderate difficulty, new feature

#123 Ts23/hotfix token paginacao
  package-lock.json
  src/app/app.component.spec.ts
  src/app/edit-page/edit-page.component.html
  src/app/edit-page/edit-page.component.spec.ts
  src/app/edit-page/edit-page.component.ts
  src/app/input-validator.service.ts
  src/app/login/login.component.spec.ts
  src/app/minhas-pls/minhas-pls.component.css
  src/app/minhas-pls/minhas-pls.component.html
  src/app/minhas-pls/minhas-pls.component.ts
  src/app/parliamentarian/parliamentarian.component.html
  src/app/parliamentarian/parliamentarian.component.spec.ts
  src/app/parliamentarian/parliamentarian.component.ts
  src/app/register-form/register-form.component.html
  src/app/register-form/register-form.component.spec.ts
  src/app/register-form/register-form.component.ts
  src/app/requests.service.spec.ts
  src/app/see-pl/see-pl.component.spec.ts
  src/app/see-pl/see-pl.component.ts
  src/app/see-politician-detail/see-politician-detail.component.spec.ts
  src/app/see-politician-detail/see-politician-detail.component.ts
Labels: MDS, bug, evolution, front end, hotfix, refactor, simple difficulty, technical
